[package]
name = "ribbit"
license = "GPL-3.0-only"
version = "0.1.0"
authors = ["Emil Lauridsen <mine809@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
mailparse = "0.13.8"